In [4]:
%pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [16]:
import pandas as pd

happy_life=pd.read_excel('data/대한민국 삶의 만족도.xlsx',engine='openpyxl')
life_merge=happy_life.groupby('시도')[['삶의 만족도']].mean()
# happy_health.head()

In [21]:
happy_health=pd.read_excel('data/대한민국 건강.xlsx',engine='openpyxl')
health=happy_health.groupby('시도')[['평균']].mean()
life_merge=pd.merge(life_merge,health.rename(columns={'평균':'건강'}),on='시도')
life_merge

           삶의 만족도      평균_x      평균_y        평균        건강
시도
강원도      0.619506  0.329506  0.329506  0.329506  0.329506
경기도      0.426023  0.353952  0.353952  0.353952  0.353952
경상남도     0.530794  0.312722  0.312722  0.312722  0.312722
경상북도     0.502223  0.264114  0.264114  0.264114  0.264114
광주광역시    0.484480  0.632300  0.632300  0.632300  0.632300
대구광역시    0.363988  0.482325  0.482325  0.482325  0.482325
대전광역시    0.407580  0.663580  0.663580  0.663580  0.663580
부산광역시    0.362081  0.511906  0.511906  0.511906  0.511906
서울특별시    0.490972  0.569532  0.569532  0.569532  0.569532
세종특별자치시  0.907700  0.232000  0.232000  0.232000  0.232000
울산광역시    0.471980  0.420040  0.420040  0.420040  0.420040
인천광역시    0.411480  0.339620  0.339620  0.339620  0.339620
전라남도     0.547709  0.424732  0.424732  0.424732  0.424732
전라북도     0.608193  0.421300  0.421300  0.421300  0.421300
제주특별자치도  0.711300  0.253700  0.253700  0.253700  0.253700
충청남도     0.553100  0.347433  0.347433  0.347433  0.347433
충청북도     0.410100  0.401064  0.401064  0.401064  0.401064

In [26]:
import os

path='data/'
file_list=os.listdir(path)

file_list

['대한민국행복지도_경제.xlsx',
 '대한민국 삶의 만족도.xlsx',
 '한국도로교통공단_시도 시군구별 교통사고 통계_20231231.csv',
 '대한민국행복지도_환경.xlsx',
 '대한민국행복지도_관계와 사회.xlsx',
 '대한민국 건강.xlsx',
 '~$대한민국 삶의 만족도.xlsx',
 '대한민국행복지도_여가.xlsx',
 '대한민국행복지도_교육.xlsx',
 '대한민국행복지도_안전.xlsx']

In [27]:
keywords={'건강':'happy_health','안전':'happy_safe','환경':'happy_environ','경제':'happy_econo',
          '교육':'happy_edu','관계및사회참여':'happy_relation','여가':'happy_leisure'}


try:
    for i in file_list:
        if i.endswith('.xlsx'):
            for x,y in keywords.item():
                if x in i:
                    keywords[x]=pd.read_excel(path+i,engine='openpyxl')
                    health=keywords[x].groupby('시도')[['평균']].mean()
                    happy_merge=pd.merge(happy_merge,health.rename(columns={'평균':x}),on='시도')
except:
    print(i)

대한민국행복지도_경제.xlsx